### PR TITLE
some tweaks

### PR DESCRIPTION
**Pull request by brikou**
see commit message to get it ;)

### CODE REVIEW

**Comment by fzaninotto** [comment]
Please make several PRs instead of one big one with unrelated changes

**Comment by brikou** [comment]
@fzaninotto tell me if you are fine with this PR (promise next time i'll try to do more atomic PR)

**Comment by fzaninotto** [comment]
Well, considering the number of back and forth commits, I'd like it better if you rebased.

**Comment by brikou** [comment]
i'll do separates PR
@fzaninotto done (readme will be change after you accept that PR because it is resulting of this)

**Pull request closed without merging**
