### PR TITLE
fixed twig's submodule entry

### PR DESCRIPTION
**Pull request by brikou**

### CODE REVIEW

**Comment by fzaninotto** [comment]
What is the nature of the change? A small description would help, as following the hash in the submodule is kinda tedious.

**Comment by brikou** [comment]
in fact when doing a git clone --recursive, i get an error because this twig commit doesn't exist anymore or is not available, i don't know

**Comment by fzaninotto** [comment]
Well, https://github.com/fabot/Twig/commit/17f814223be3823879700e902fb475b7890ad530 leads to a 404. Not sure how submodules track dependencies, though. can you point the commit you want to track?

**Comment by brikou** [comment]
you made a typo `fabot` instead of `fabpot`

**Comment by fzaninotto** [comment]
ah, you got me!

**Pull request merged**
