### PR TITLE
fixed empty lines from rendering, and few improvement in docblock and fix

### PR DESCRIPTION
**Pull request by brikou**
Hello François, here is another PR ;)
- fixed empty lines from rendering (no more double empty lines)
- few improvement in docblock (real type instread of mixed, and removed unnecessary dot)
- fixed fromArray method which prevent passing 'null' values

### CODE REVIEW

**Comment by fzaninotto** [comment]
I'm not fond of the type hint on set/add/remove methods for one-to-many relationships. It creates many problems when using proxy objects. Could you remove this change from the PR? Other than that, I'm fine with the PR.

Lastly, PRs are much easier to merge when they are atomic. I don't mind merging 5 small PRs rather than 1 big one.

**Comment by brikou** [comment]
@fzaninotto ok I removed type hint from my PR, about atomic PR I agree, I'll try to make it better next time ;)

**Comment by fzaninotto** [comment]
Sorry, one last request: can you remove my commit merging your previous branch from the PR? I think it conflicts.

**Comment by brikou** [comment]
@fzaninotto i made a rebase guess it worked, can we talk through irc ;)

**Comment by brikou** [comment]
@fzaninotto tell me if you want a new clean PR

**Pull request merged**
