### PR TITLE
[Template] switch statement + fromArray calls setByName

### PR DESCRIPTION
**Pull request by brikou**
- added missing slash + typo
- made use of switch statement in generic setter/getter
- method `fromArray` calls `setByName` which handles perfectly exception when generic setter is not defined

### CODE REVIEW

**Comment by fzaninotto** [comment]
I fail to see the added value of your change. It's a different approach, but it doesn't perform better, and it adds no feature. 

Please submit PRs that add functionality instead.

**Comment by brikou** [comment]
it does a lot o tweaks (improve code readability) but major thing is to **delegate exception handling from `fromArray` to `setByName`**

NB: please don't be to rude by closing PR without asking the real purpose if it is not clear ?

**Comment by fzaninotto** [comment]
Throwing an exception in fromArray() can be an undesired effect, especially
if the array comes from a web form.

Besides, the fromArray() implementation provides the same API as in Propel1
- which should be a general guideline.

2011/5/9 brikou <
reply@reply.github.com>

**Comment by brikou** [comment]
Ok now you can close this PR but I thought that post parameters shouldn't be trusted in anyway,...

**Pull request closed without merging**
